/*
* Action Types.
*/
export const types =
{
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  RESET_PRICE_LEVEL: 'RESET_PRICE_LEVEL',
  SET_PRICE_LEVEL: 'SET_PRICE_LEVEL',
  SET_NUMERIC_KEYBUFFER: 'SET_NUMERIC_KEYBUFFER',
  APPEND_NUMERIC_KEYBUFFER: 'APPEND_NUMERIC_KEYBUFFER',
  COMPLETE_SALE: 'COMPLETE_SALE'
};

/*
* Other constants.
*/
