/*
* Action Types.
*/
export const types =
{
  SET_SELECTED_SALEITEM_INDEX: 'SET_SELECTED_SALEITEM_INDEX',
  FAST_PLU: 'FAST_PLU',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  REMOVE_SELECTED_ITEM: 'REMOVE_SELECTED_ITEM',
  RESET_PRICE_LEVEL: 'RESET_PRICE_LEVEL',
  SET_PRICE_LEVEL: 'SET_PRICE_LEVEL',
  SET_NUMERIC_KEYBUFFER: 'SET_NUMERIC_KEYBUFFER',
  APPEND_NUMERIC_KEYBUFFER: 'APPEND_NUMERIC_KEYBUFFER',
  COMPLETE_SALE: 'COMPLETE_SALE',
  FASTPLU: "FASTPLU",
  FASTPLU_REQUEST: "FASTPLU_REQUEST",
};

/*
* Other constants.
*/
